using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IMS.Web.DataAccess.Entities
{
    public class Product
    {
        /// <summary>
        /// Autogenerated Identity Number
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Required]
        [StringLength(100,ErrorMessage ="product cannot exceed 100 character")]
        public string Name { get; set; }

        [StringLength(250, ErrorMessage = "product cannot exceed 100 character")]
        public string Description { get; set; }

        [Required]
        [Range(0.01, 10000.00, ErrorMessage = "The price must be between 0.01 and 10000.00.")]
        [Column(TypeName = "decimal(18,2)")]
        public decimal PurchasePrice { get; set; }

        [Required]
        [Range(0.01, 10000.00, ErrorMessage = "The price must be between 0.01 and 10000.00.")]
        [Column(TypeName = "decimal(18,2)")]
        public decimal SellingPrice { get; set; }

        [Required]
        [Range(0, 1000, ErrorMessage = "The stock quantity must be between 0 and 1000.")]
        public int Stock { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Date Added")]
        public DateTime DateAdded { get; set; }

    }
}
